title: Many Tiny Things
description: >
  Explorable explanations about how everything is made up of many tiny things.
baseurl: ""
url: "http://example.com" # TODO: change this


defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"

kramdown:
    parse_block_html: true