title: Many Tiny Things
description: >
  Explorable explanations on how all big things are made up of many tiny things.
baseurl: ""
url: "http://example.com" # TODO: change this
permalink: /:year/:month/:title

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "two_column_explanation"

kramdown:
    parse_block_html: true